<a href="https://colab.research.google.com/github/MrCalmTam/AI_NORON/blob/main/AI_24_03_ANN_CRABS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
wl = '/content/crabs.csv'
data=pd.read_csv(wl)
data.head()

from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score # sai so , do chinh xac
from sklearn.preprocessing import StandardScaler # chuan hoa du lieu, ti le

In [ ]:
data = data.replace(to_replace=["B" ],value="0")
data = data.replace(to_replace=["O" ],value="1")
data = data.replace(to_replace=["M" ],value="1")
data = data.replace(to_replace=["F" ],value="0")
data

    speies sex  index  fontallip  rearwidth  length  width  depth
0        0   1      1        8.1        6.7    16.1   19.0    7.0
1        0   1      2        8.8        7.7    18.1   20.8    7.4
2        0   1      3        9.2        7.8    19.0   22.4    7.7
3        0   1      4        9.6        7.9    20.1   23.1    8.2
4        0   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      1   0     46       21.4       18.0    41.2   46.2   18.7
196      1   0     47       21.7       17.1    41.7   47.2   19.6
197      1   0     48       21.9       17.2    42.6   47.4   19.5
198      1   0     49       22.5       17.2    43.0   48.7   19.8
199      1   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [ ]:
iris=datasets.load_iris() 
X = iris.data
Y = iris.target

In [ ]:
X = data.iloc[:,0:8]
Y = data.iloc[:,1]

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)
sc=StandardScaler()  #dat ham 
sc.fit(X_train)   
X_train_std=sc.transform(X_train) # chuyen du lieu x tran thanh std 
X_test_std=sc.transform(X_test)   # chuyen du lieu x tran thanh std

In [ ]:
model = Perceptron(max_iter = 100 ,eta0 = 0.1 , random_state =0 )   # day cho no hoc , max_iter la so lan hoc, eta0 la toc do hoc tu 0 ->1.
model.fit(X_train_std,Y_train)
Y_pred=model.predict(X_test_std)
print(Y_pred)
print(Y_test)
print(' ĐỘ CHÍNH XÁC CỦA MÔ HÌNH SCALE :',accuracy_score(Y_test,Y_pred))

['1' '1' '1' '0' '0' '1' '0' '1' '0' '0' '1' '1' '0' '1' '0' '1' '1' '0'
 '0' '0' '1' '0' '0' '0' '0' '0' '0' '0' '1' '0' '0' '1' '1' '1' '0' '0'
 '1' '1' '1' '0' '0' '1' '0' '1' '1' '1' '1' '0' '1' '1' '1' '0' '1' '0'
 '0' '1' '0' '1' '0' '0']
33     1
46     1
131    1
83     0
174    0
148    1
173    0
1      1
58     0
170    0
137    1
129    1
63     0
127    1
198    0
149    1
124    1
70     0
160    0
178    0
116    1
73     0
159    0
74     0
64     0
97     0
184    0
59     0
47     1
69     0
151    0
3      1
130    1
113    1
165    0
88     0
108    1
29     1
27     1
51     0
153    0
105    1
167    0
21     1
32     1
10     1
144    1
180    0
45     1
147    1
25     1
199    0
132    1
56     0
81     0
37     1
77     0
7      1
150    0
72     0
Name: sex, dtype: object
 ĐỘ CHÍNH XÁC CỦA MÔ HÌNH SCALE : 1.0